### ISSUE TITLE
Question concerning instructor registration

### ISSUE THREAD

**Issue by baptboleat** [2020-2021-ECOM-INFO5-G6/app#35]
While discussing about coming issues, we had a question concerning instructor registration. In the scenarios, the way how they register is not evoked. We had 2 ideas : 
- The manager (gestionnaire) gives a code to the instructor (moniteur) who wants to create an account. The instructor has to put this code in a corresponding field in the registration form.
- Everybody can register as an instructor, but the manager has to validate each newly created instructor account before he can do something.

Which one would be the best for the client ?

**Comment by SybilleCaffiau** [comment]
Vous n'avez pas de scénario pour l'enregistrement des instructeurs car ce n'est pas à faire. L'utilisation de ce qui est généré automatiquement par JHipser sera suffisant. Le gestionnaire (qui sera le seul à utiliser la partie générée par JHipster comme un administrateur) créera les moniteurs.
