### ISSUE TITLE
Correct orthograph errors and lacking translations

### ISSUE THREAD

**Issue by baptboleat** [2020-2021-ECOM-INFO5-G6/app#99]
**As an** user
**I want** to have everything either in (correct) english or in french but no mixed french-english 

Description :

Hints :
- choisir**e**
- plat**e**form
- navbar text is only in english
- price indication is only in english
- some others...

Assignees :

**Comment by vernemax** [comment]
In this issue I will also : 
- Change the navbar picture
- Merge with my debug branch which have some corrected bug
( instructor access denied etc.. )
